// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPuEQRay8h1KCA7s01t0SkCrSFbHT-ebc',
    appId: '1:13971597827:web:9ece44dfa77b9487f83c36',
    messagingSenderId: '13971597827',
    projectId: 'resq-106ed',
    authDomain: 'resq-106ed.firebaseapp.com',
    storageBucket: 'resq-106ed.firebasestorage.app',
    measurementId: 'G-558F55HLV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZO6P89MG9IPjIQmI55h7Z6njpS515H8M',
    appId: '1:13971597827:android:28dfcba44561fffff83c36',
    messagingSenderId: '13971597827',
    projectId: 'resq-106ed',
    storageBucket: 'resq-106ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhK-u4AkmeJ7OhKTFPuV-pjuANLKools',
    appId: '1:13971597827:ios:f3f067b37f973e09f83c36',
    messagingSenderId: '13971597827',
    projectId: 'resq-106ed',
    storageBucket: 'resq-106ed.firebasestorage.app',
    iosBundleId: 'com.vaibhav.resq',
  );
}
