// Central icon re-exports.
//
// Why this file exists: lucide-react-native has renamed a handful of icons
// across versions (e.g. AlertTriangle -> TriangleAlert, Home -> House). By
// importing icons from here instead of 'lucide-react-native' directly, a
// future version bump only needs a fix in this one file instead of a
// project-wide find/replace.
import {
  Activity,
  TriangleAlert as AlertTriangle,
  Bell,
  BellOff,
  BriefcaseMedical,
  Camera,
  CalendarDays,
  CarFront,
  Check,
  ChevronRight,
  Clock3,
  CloudRain,
  Droplets,
  Flashlight,
  House as HomeIcon,
  ImagePlus,
  Info,
  LockKeyhole,
  LogIn,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Navigation,
  Phone,
  Plus,
  Radio,
  Send,
  ShieldCheck,
  Sparkles,
  Users,
  Volume2,
  X,
  ArrowLeft,
  CircleHelp,
  FileText,
  Heart,
  LifeBuoy,
  Ellipsis as MoreHorizontal,
  User,
  Wifi,
  WifiOff,
  RefreshCw,
  CircleAlert as AlertCircle,
  Sun,
  Moon,
  MonitorSmartphone,
  Mail,
  Scale,
  Keyboard,
} from 'lucide-react-native';

export {
  Activity,
  AlertTriangle,
  Bell,
  BellOff,
  BriefcaseMedical,
  Camera,
  CarFront,
  Check,
  ChevronRight,
  Clock3,
  CloudRain,
  Droplets,
  Flashlight,
  HomeIcon,
  ImagePlus,
  Info,
  LockKeyhole,
  LogIn,
  MapPin,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Navigation,
  Phone,
  Plus,
  Radio,
  Send,
  ShieldCheck,
  Sparkles,
  Users,
  Volume2,
  X,
  ArrowLeft,
  CircleHelp,
  Sun,
  Moon,
  MonitorSmartphone,
  FileText,
  Heart,
  LifeBuoy,
  MoreHorizontal,
  User,
  Wifi,
  WifiOff,
  RefreshCw,
  AlertCircle,
  Mail,
  CalendarDays,
  Scale,
  Keyboard,
};
